{{- define "config-logging" -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-logging-triggers
data:
  zap-logger-config: |
    {{ $.Values.config.zap_logger_config | toJson }}
  loglevel.controller: {{ $.Values.config.loglevel.controller | quote }}
  loglevel.webhook: {{ $.Values.config.loglevel.webhook | quote }}
  loglevel.eventlistener: {{ $.Values.config.loglevel.eventlistener | quote }}
...
{{- end -}}
{{- include "helpers.template.overlay" ( dict "Global" $ "template_definition" "config-logging" ) }}
