{{- define "config-observability" -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-observability-triggers
data:
{{- $.Values.configobservability | toYaml | nindent 2 }}
{{- end -}}
{{- include "helpers.template.overlay" ( dict "Global" $ "template_definition" "config-observability" ) }}
