{{- define "mutatingwebhookconfig-webhook" -}}
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: webhook.triggers.tekton.dev
webhooks:
  - admissionReviewVersions:
      - v1beta1
    clientConfig:
      service:
        name: tekton-triggers-webhook
        namespace: {{ $.Release.Namespace }}
    failurePolicy: Fail
    sideEffects: None
    name: webhook.triggers.tekton.dev
...
{{- end -}}
{{- include "helpers.template.overlay" ( dict "Global" $ "template_definition" "mutatingwebhookconfig-webhook" ) }}
