{{- define "secret-triggers" -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: triggers-webhook-certs
...
{{- end -}}
{{- include "helpers.template.overlay" ( dict "Global" $ "template_definition" "secret-triggers" ) }}
