loki:
  enabled: true
  persistence:
    enabled: true
  ingress:
    enabled: true
    hosts:
      - host: loki.jarvis.local
        paths: ["/"]
    annotations:
      cert-manager.io/cluster-issuer: jarvis-ca-issuer
    tls:
     - secretName: lokistack-loki-tls
       hosts:
         - loki.jarvis.local

promtail:
  enabled: true

grafana:
  adminPassword: password
  enabled: true
  persistence:
    enabled: true
  grafana.ini:
    auth.anonymous:
      enabled: true
      org_name: Main Org.
      org_role: Viewer
  ingress:
    enabled: true
    path: /
    hosts:
      - grafana.jarvis.local
    annotations:
      cert-manager.io/cluster-issuer: jarvis-ca-issuer
    tls:
     - secretName: lokistack-grafana-tls
       hosts:
         - grafana.jarvis.local
  dashboardProviders:
   dashboardproviders.yaml:
     apiVersion: 1
     providers:
     - name: 'default'
       orgId: 1
       folder: ''
       type: file
       disableDeletion: false
       editable: true
       options:
         path: /var/lib/grafana/dashboards/default
  dashboards:
    default:
      tekton-pipelines:
        json: |
          {
            "annotations": {
              "list": [
                {
                  "builtIn": 1,
                  "datasource": "-- Grafana --",
                  "enable": true,
                  "hide": true,
                  "iconColor": "rgba(0, 211, 255, 1)",
                  "name": "Annotations & Alerts",
                  "type": "dashboard"
                }
              ]
            },
            "description": "Tekton Logs Dashboard",
            "editable": true,
            "gnetId": null,
            "graphTooltip": 0,
            "id": null,
            "iteration": 1610656127596,
            "links": [],
            "panels": [
              {
                "aliasColors": {},
                "bars": true,
                "dashLength": 10,
                "dashes": false,
                "datasource": "Loki",
                "fieldConfig": {
                  "defaults": {
                    "custom": {}
                  },
                  "overrides": []
                },
                "fill": 1,
                "fillGradient": 0,
                "gridPos": {
                  "h": 8,
                  "w": 24,
                  "x": 0,
                  "y": 0
                },
                "hiddenSeries": false,
                "id": 6,
                "legend": {
                  "avg": false,
                  "current": false,
                  "max": false,
                  "min": false,
                  "show": false,
                  "total": false,
                  "values": false
                },
                "lines": false,
                "linewidth": 1,
                "nullPointMode": "null",
                "options": {
                  "dataLinks": []
                },
                "percentage": false,
                "pointradius": 2,
                "points": false,
                "renderer": "flot",
                "seriesOverrides": [],
                "spaceLength": 10,
                "stack": false,
                "steppedLine": false,
                "targets": [
                  {
                    "expr": "sum(count_over_time({namespace=~\"$namespace\", tekton_dev_pipeline=~\"$tekton_dev_pipeline\", tekton_dev_pipelineRun=~\"$tekton_dev_pipelineRun\", tekton_dev_taskRun=~\"$tekton_dev_taskRun\"} |~ \"$search\"[$__interval]))",
                    "refId": "A"
                  }
                ],
                "thresholds": [],
                "timeFrom": null,
                "timeRegions": [],
                "timeShift": null,
                "title": "Timeline",
                "tooltip": {
                  "shared": true,
                  "sort": 0,
                  "value_type": "individual"
                },
                "type": "graph",
                "xaxis": {
                  "buckets": null,
                  "mode": "time",
                  "name": null,
                  "show": true,
                  "values": []
                },
                "yaxes": [
                  {
                    "format": "short",
                    "label": null,
                    "logBase": 1,
                    "max": null,
                    "min": null,
                    "show": false
                  },
                  {
                    "format": "short",
                    "label": null,
                    "logBase": 1,
                    "max": null,
                    "min": null,
                    "show": false
                  }
                ],
                "yaxis": {
                  "align": false,
                  "alignLevel": null
                }
              },
              {
                "datasource": "Loki",
                "fieldConfig": {
                  "defaults": {
                    "custom": {}
                  },
                  "overrides": []
                },
                "gridPos": {
                  "h": 25,
                  "w": 24,
                  "x": 0,
                  "y": 8
                },
                "id": 2,
                "maxDataPoints": "",
                "options": {
                  "showLabels": true,
                  "showTime": true,
                  "sortOrder": "Descending",
                  "wrapLogMessage": true
                },
                "targets": [
                  {
                    "expr": "{namespace=~\"$namespace\", tekton_dev_pipeline=~\"$tekton_dev_pipeline\", tekton_dev_pipelineRun=~\"$tekton_dev_pipelineRun\", tekton_dev_taskRun=~\"$tekton_dev_taskRun\"} |~ \"$search\"",
                    "refId": "A"
                  }
                ],
                "timeFrom": null,
                "timeShift": null,
                "title": "Logs",
                "type": "logs"
              }
            ],
            "refresh": false,
            "schemaVersion": 22,
            "style": "dark",
            "tags": [],
            "templating": {
              "list": [
                {
                  "allValue": null,
                  "current": {
                    "selected": false,
                    "text": "All",
                    "value": "$__all"
                  },
                  "datasource": "Loki",
                  "definition": "label_values(kube_pod_info, namespace)",
                  "hide": 0,
                  "includeAll": true,
                  "index": -1,
                  "label": null,
                  "multi": false,
                  "name": "namespace",
                  "options": [],
                  "query": "label_values(kube_pod_info, namespace)",
                  "refresh": 1,
                  "regex": "",
                  "skipUrlSync": false,
                  "sort": 0,
                  "tagValuesQuery": "",
                  "tags": [],
                  "tagsQuery": "",
                  "type": "query",
                  "useTags": false
                },
                {
                  "allValue": ".*",
                  "current": {
                    "selected": false,
                    "text": "All",
                    "value": "$__all"
                  },
                  "datasource": "Loki",
                  "definition": "label_values(mixin_pod_workload{namespace=\"$namespace\"}, tekton_dev_pipeline)",
                  "hide": 0,
                  "includeAll": true,
                  "index": -1,
                  "label": null,
                  "multi": false,
                  "name": "tekton_dev_pipeline",
                  "options": [],
                  "query": "label_values(mixin_pod_workload{namespace=\"namespace\"}, tekton_dev_pipeline)",
                  "refresh": 1,
                  "regex": "",
                  "skipUrlSync": false,
                  "sort": 5,
                  "tagValuesQuery": "",
                  "tags": [],
                  "tagsQuery": "",
                  "type": "query",
                  "useTags": false
                },
                {
                  "allValue": ".*",
                  "current": {
                    "selected": false,
                    "text": "All",
                    "value": "$__all"
                  },
                  "datasource": "Loki",
                  "definition": "label_values(mixin_pod_workload{namespace=\"$namespace\"}, tekton_dev_pipelineRun)",
                  "hide": 0,
                  "includeAll": true,
                  "index": -1,
                  "label": null,
                  "multi": false,
                  "name": "tekton_dev_pipelineRun",
                  "options": [],
                  "query": "label_values(mixin_pod_workload{namespace=\"$namespace\"}, tekton_dev_pipelineRun)",
                  "refresh": 1,
                  "regex": "",
                  "skipUrlSync": false,
                  "sort": 5,
                  "tagValuesQuery": "",
                  "tags": [],
                  "tagsQuery": "",
                  "type": "query",
                  "useTags": false
                },
                {
                  "allValue": ".*",
                  "current": {
                    "selected": false,
                    "text": "All",
                    "value": "$__all"
                  },
                  "datasource": "Loki",
                  "definition": "label_values(mixin_pod_workload{namespace=\"$namespace\"}, tekton_dev_taskRun)",
                  "hide": 0,
                  "includeAll": true,
                  "index": -1,
                  "label": null,
                  "multi": false,
                  "name": "tekton_dev_taskRun",
                  "options": [],
                  "query": "label_values(mixin_pod_workload{namespace=\"$namespace\"}, tekton_dev_taskRun)",
                  "refresh": 1,
                  "regex": "",
                  "skipUrlSync": false,
                  "sort": 5,
                  "tagValuesQuery": "",
                  "tags": [],
                  "tagsQuery": "",
                  "type": "query",
                  "useTags": false
                },
                {
                  "current": {
                    "selected": false,
                    "text": "",
                    "value": ""
                  },
                  "hide": 0,
                  "label": null,
                  "name": "search",
                  "options": [
                    {
                      "selected": true,
                      "text": "",
                      "value": ""
                    }
                  ],
                  "query": "",
                  "skipUrlSync": false,
                  "type": "textbox"
                }
              ]
            },
            "time": {
              "from": "now-24h",
              "to": "now"
            },
            "timepicker": {
              "refresh_intervals": [
                "10s",
                "30s",
                "1m",
                "5m",
                "15m",
                "30m",
                "1h",
                "2h",
                "1d"
              ]
            },
            "timezone": "",
            "title": "Tekton Logs Dashboard",
            "uid": "tektonDash",
            "variables": {
              "list": []
            },
            "version": 1
          }