{{- define "ClusterRoleBinding-el" -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "helpers.labels.fullname" . }}-el
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "helpers.labels.fullname" . }}-el
subjects:
  - kind: ServiceAccount
    name: {{ template "helpers.labels.fullname" . }}-el
    namespace: {{ $.Release.Namespace }}
...
{{- end -}}
{{- include "helpers.template.overlay" ( dict "Global" $ "template_definition" "ClusterRoleBinding-el" ) }}