{{- define "ServiceAccount-el" -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "helpers.labels.fullname" . }}-el
...
{{- end -}}
{{- include "helpers.template.overlay" ( dict "Global" $ "template_definition" "ServiceAccount-el" ) }}