{{- define "Secret-project" -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "helpers.labels.fullname" . }}
  labels: {{- include "helpers.labels.labels" . | nindent 4 }}
data:
  gerrit-username: "{{ b64enc .Values.params.gerrit.user }}"
  gerrit-authfile: "{{ b64enc ( printf "%s:%s" .Values.params.gerrit.user .Values.params.gerrit.password ) }}"
  gerrit-ssh-key: "{{ b64enc ( .Values.params.gerrit.ssh_key ) }}"
...
{{- end -}}
{{- include "helpers.template.overlay" ( dict "Global" $ "template_definition" "Secret-project" ) }}