{{- if $.Values.clusterRole.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ $.Values.clusterRole.name }}
rules:
  # EventListeners need to be able to fetch any clustertriggerbindings
   - apiGroups: ["triggers.tekton.dev"]
     resources: ["clustertriggerbindings"]
     verbs: ["get", "list", "watch"]
{{- end }}
