{{- define "Service-dex" -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "helpers.labels.fullname" . }}
  labels: {{- include "helpers.labels.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: {{ .Values.params.endpoints.port.http }}
    nodePort: {{ .Values.params.endpoints.nodePort.http }}
    targetPort: 80
    protocol: TCP
  - name: https
    port: {{ .Values.params.endpoints.port.https }}
    nodePort: {{ .Values.params.endpoints.nodePort.https }}
    targetPort: 443
    protocol: TCP
  selector: {{- include "helpers.labels.matchLabels" . | nindent 4 }}
...
{{- end -}}
{{- include "helpers.template.overlay" ( dict "Global" $ "template_definition" "Service-dex" ) }}